// npm run test:benches -- roleFacts
import assert from 'node:assert/strict';
import { reduceRoleFacts, roleFactsForAudience, type RoleFactsContext } from '../apps/server/src/prompt/roleFacts.js';
let checks = 0;
const ok = (name: string, fn: () => void) => { fn(); console.log(`ok ${++checks} ${name}`); };
const ctx: RoleFactsContext = { conversationId: 'room', pathIds: new Set(['u1','a1','u2','a2']),
  visibleIds: new Set(['u1','a1','u2','a2']), actorIds: new Set(['npc']), speakerByMessage: new Map([['a1','npc'],['a2','npc']]) };
const register = { id:'e1', proposal_id:'p', conversation_id:'room', anchor_message_id:'u1', expected_version:0, recorded_by:'human', action:'register',
  proposal:{ kind:'role', subject_id:'user', description:'방문객 안내', proposed_by:'npc', source_message_ids:['a1'], audience:{visibility:'public'} } };
const decision = (action: string, version = 1) => ({id:'e2', proposal_id:'p', conversation_id:'room', anchor_message_id:'u2', expected_version:version, recorded_by:'human', action, decision_by:'user'});
const claim = {id:'e3',proposal_id:'p',conversation_id:'room',anchor_message_id:'u2',expected_version:1,recorded_by:'human',action:'record_claim',speaker_id:'npc',source_message_id:'a2',claimed_status:'accepted'};
ok('registration never infers acceptance from text', () => { const state=reduceRoleFacts([register],ctx);assert.equal(state.facts[0].status,'proposed');assert.equal(state.facts[0].decision_by,null);assert.throws(()=>reduceRoleFacts([{...register,status:'accepted'}],ctx)); });
ok('user-owned role requires user decision, not NPC or model fields', () => {assert.throws(()=>reduceRoleFacts([register,{...decision('accept'),decision_by:'npc'}],ctx));assert.throws(()=>reduceRoleFacts([register,{...decision('accept'),model_decision:true}],ctx));assert.equal(reduceRoleFacts([register,decision('accept')],ctx).facts[0].status,'accepted');});
ok('withdrawal is explicit and later acceptance is a new event', () => {const events=[register,decision('accept'),{...decision('withdraw_acceptance',2),id:'e4'},{...decision('accept',3),id:'e5'}];const old=reduceRoleFacts(events.slice(0,3),ctx).facts[0];assert.equal(old.status,'rejected');assert.equal(old.last_decision,'withdraw_acceptance');assert.equal(reduceRoleFacts(events,ctx).facts[0].version,4);assert.throws(()=>reduceRoleFacts([register,decision('withdraw_acceptance')],ctx));});
ok('idempotent events and stale versions have different outcomes',()=>{assert.equal(reduceRoleFacts([register,register],ctx).facts[0].version,1);assert.throws(()=>reduceRoleFacts([register,{...register,recorded_by:'other'}],ctx));assert.throws(()=>reduceRoleFacts([register,decision('accept',2)],ctx));});
ok('NPC assertion records conflict without deciding status',()=>{const state=reduceRoleFacts([register,claim],ctx);assert.equal(state.facts[0].status,'proposed');assert.equal(state.conflicts[0].actual_status_at_claim,'proposed');assert.throws(()=>reduceRoleFacts([register,{...claim,speaker_id:'user'}],ctx));});
ok('claim judged at its event time, not against a later withdrawal',()=>{const state=reduceRoleFacts([register,decision('accept'),{...claim,expected_version:2},{...decision('withdraw_acceptance',3),id:'e4'}],ctx);assert.equal(state.conflicts.length,0);assert.equal(state.facts[0].status,'rejected');});
ok('foreign room, unknown actors and audience IDs fail closed',()=>{assert.throws(()=>reduceRoleFacts([{...register,conversation_id:'other'}],ctx));assert.throws(()=>reduceRoleFacts([{...register,proposal:{...register.proposal,subject_id:'absent'}}],ctx));assert.throws(()=>reduceRoleFacts([{...register,proposal:{...register.proposal,audience:{visibility:'private',recipient_ids:['absent']}}}],ctx));});
ok('off-branch events cannot restore or change current state',()=>{const branch={...ctx,pathIds:new Set(['u1','a1']),visibleIds:new Set(['u1','a1'])};assert.equal(reduceRoleFacts([register,decision('accept')],branch).facts[0].status,'proposed');assert.equal(reduceRoleFacts([{...register,anchor_message_id:'elsewhere'},decision('accept')],ctx).facts.length,0);});
ok('private evidence excludes whole fact rather than exposing stale public acceptance',()=>{const limited={...ctx,visibleIds:new Set(['u1','a1'])};assert.equal(reduceRoleFacts([register,decision('accept')],limited).facts.length,0);});
ok('fact audience excludes observer even when source is otherwise visible',()=>{const state=reduceRoleFacts([{...register,proposal:{...register.proposal,audience:{visibility:'private',recipient_ids:['user'],observer_ids:['gm']}}}],ctx);assert.equal(roleFactsForAudience(state,'gm').facts.length,0);assert.equal(roleFactsForAudience(state,'user').facts.length,1);});
ok('reduction never mutates input records',()=>{const before=JSON.stringify([register,claim]);reduceRoleFacts([register,claim],ctx);assert.equal(JSON.stringify([register,claim]),before);});
